tbl <- read.csv('ratings.csv');
y <- tbl$avg_rating;
permutation = sample.int(length(y));
train_prop = 0.8;
y_train = y[permutation[1:as.integer(length(y)*train_prop)]];
y_test = y[permutation[(as.integer(length(y)*train_prop)+1):length(y)]];
y = y_train;

nu0 = 1;
sigmasq0 = 1;
k0 = 0.1;
mu01 = 2.5;
mu02 = 2.5;
num_components = 2;
ber_p1 <- array(data=0.5, dim=length(y));
ber_p2 <- array(data=1-ber_p1[1],dim=length(y));
sig1alpha <- 1;
sig1beta <- 0.5*nu0*sigmasq0
sig2alpha <- 1;
sig2beta <- 0.5*nu0*sigmasq0;
lambda1 <- 2.5;
tau1 <- sigmasq0/k0;
lambda2 <- 2.5;
tau2 <- sigmasq0/k0;
alpha_alpha <- 1;
alpha_beta <- 1;

itermax = 5000;
lambda1_vals = array(dim=itermax);
lambda2_vals = array(dim=itermax);
tau1_vals = array(dim=itermax);
tau2_vals = array(dim=itermax);
sig1alpha_vals = array(dim=itermax);
sig1beta_vals = array(dim=itermax);
alpha_alpha_vals = array(dim=itermax);
alpha_beta_vals = array(dim=itermax);

iters = 1;
while (iters <= itermax) {
    neg_log_sigsq1 = digamma(sig1alpha)-log(sig1beta);
    neg_log_sigsq2 = digamma(sig2alpha)-log(sig2beta);
    reciprocal_sigsq1 = sig1alpha/sig1beta;
    reciprocal_sigsq2 = sig2alpha/sig2beta;
    mu1_sq = tau1+lambda1^2;
    mu2_sq = tau2+lambda2^2;
    log_alpha = digamma(alpha_alpha)-digamma(alpha_alpha+alpha_beta);
    log_1minus_alpha = digamma(alpha_beta)-digamma(alpha_alpha+alpha_beta);
    w = 0.5*neg_log_sigsq1-0.5*reciprocal_sigsq1*(y^2-2*lambda1*y+mu1_sq)-0.5*neg_log_sigsq2+0.5*reciprocal_sigsq2*(y^2-2*lambda2*y+mu2_sq)+log_alpha-log_1minus_alpha;
    ber_p1 = exp(w)/(1+exp(w));
    ber_p2 = 1-ber_p1;
    sig1alpha = 0.5*(sum(ber_p1)+nu0);
    sig1beta = 0.5*(nu0*sigmasq0+sum(ber_p1*(y^2-2*y*lambda1+mu1_sq))+k0*(mu01^2-2*mu01*lambda1+mu1_sq));
    sig2alpha = 0.5*(sum(ber_p2)+nu0);
    sig2beta = 0.5*(nu0*sigmasq0+sum(ber_p2*(y^2-2*y*lambda2+mu2_sq))+k0*(mu02^2-2*mu02*lambda2+mu2_sq));
    reciprocal_sigsq1 = sig1alpha/sig1beta;
    reciprocal_sigsq2 = sig2alpha/sig2beta;
    lambda1 = (sum(ber_p1*y)+k0*mu01)/(sum(ber_p1)+k0);
    lambda1_vals[iters] = lambda1;
    tau1 = 1/(reciprocal_sigsq1*(sum(ber_p1)+k0));
    lambda2 = (sum(ber_p2*y)+k0*mu02)/(sum(ber_p2)+k0);
    lambda2_vals[iters] = lambda2;
    tau2 = 1/(reciprocal_sigsq2*(sum(ber_p2)+k0));
    tau1_vals[iters] = tau1;
    tau2_vals[iters] = tau2;
    sig1alpha_vals[iters] = sig1alpha;
    sig1beta_vals[iters] = sig1beta;
    alpha_alpha = sum(ber_p1)+1;
    alpha_beta = sum(ber_p2)+1;
    alpha_alpha_vals[iters] = alpha_alpha;
    alpha_beta_vals[iters] = alpha_beta;
    iters = iters+1;
}

plot(1:itermax, lambda1_vals, main='lambda1');
dev.new();
plot(1:itermax, lambda2_vals, main='lambda2');
dev.new();
plot(1:itermax, tau1_vals, main='tau1');
dev.new();
plot(1:itermax, tau2_vals, main='tau2');
dev.new();
plot(1:itermax, sig1alpha_vals, main='sig1alpha');
dev.new();
plot(1:itermax, sig1beta_vals, main='sig1beta');
dev.new();
plot(1:itermax, alpha_alpha_vals, main='alpha_alpha');
dev.new();
plot(1:itermax, alpha_beta_vals, main='alpha_beta');
print('lambda1');
print(lambda1);
print('lambda2');
print(lambda2);
print('tau1');
print(tau1);
print('tau2');
print(tau2);
print('alpha_alpha');
print(alpha_alpha);
print('alpha_beta');
print(alpha_beta);
